### ISSUE TITLE
AtomicUpdaterTest#update()

### ISSUE THREAD

**Issue by Aery9527** [Aery9527/misty#1]
這個UT跑10次可能有2,3次失敗, 但理論上透過ReentrantLock控制應該use內的行為同一時間只有一個thread可以進入,
但結果有時候不如預期, 有試過將target加上volatile或改用AtomicReference, 問題一樣存在.

![image](https://user-images.githubusercontent.com/6187340/117937938-16aee300-b339-11eb-8a9a-4d0eb3d04b01.png)

**Comment by RandyPanGit** [comment]
我認領測試看看

**Comment by Aery9527** [comment]
發現是target更新時不在atomic裡

**Comment by RandyPanGit** [comment]
有commit的紀錄嗎

**Comment by Aery9527** [comment]
上了
